name: Integrate and deploy website

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: [ self-hosted ]
    
    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies 
      run: npm install
    
    - name: Build the project
      run: npm run build --if-present

    - name: Run unit tests 
      run: npm test

    - name: Stop Docker container
      run: |
        docker container stop website-nginx
        docker container rm website-nginx

    - name: Remove old Docker image
      run: docker image rm brain-rain-react:latest
    
    - name: Build new Docker image
      run: docker build -t brain-rain-react:latest .

    # Als naechtes dir der traefik config nutzen
